services:
  react:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: chat-app-react
    ports:
      - "5173:5173"
    # env_file:
    #   - .env
    # optional in dev if you want live code reload
    volumes:
      - .:/app
      - /app/node_modules