name: Deploy Backend to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build backend image
        run: |
          docker build ./backend \
            -f ./backend/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-node-react:node-latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-node-react:node-latest

      - name: Build frontend image
        run: |
          docker build ./frontend \
            -f ./frontend/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-node-react:react-latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-node-react:react-latest
